apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gha.fullname" . }}
  labels:
    {{- include "gha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "gha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gha.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        ports:
        - name: http
          containerPort: {{ .Values.containerPort }}
          protocol: TCP
        env:
        - name: PORT
          value: "3000"
        - name: EXPECTED_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-key-secret
              key: apiKey
        - name: NODE_ENV
          value: production
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
