apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Add Cognito as an OIDC provider
  oidc.config: |
    name: Cognito
    issuer: https://cognito-idp.${region}.amazonaws.com/${user_pool_id}
    clientID: ${client_id}
    clientSecret: ${client_secret}
    requestedScopes: ["openid", "profile", "email"]
    requestedIDTokenClaims: {"groups": {"essential": true}}
  
  # Map Cognito groups to ArgoCD roles
  policy.csv: |
    g, Admins, role:admin
    g, Developers, role:readonly

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
stringData:
  # The client secret from Cognito
  oidc.cognito.clientSecret: ${client_secret}