{{- if .Values.ingress.enabled -}}
{{- $fullName := include "github-actions-example.fullname" . -}}
{{- $svcPortName := "" }}
{{- /* Attempt to find a port named 'http', otherwise use the first port defined */}}
{{- range .Values.service.ports }}
  {{- if eq .name "http" }}
    {{- $svcPortName = .name }}
  {{- end }}
{{- end }}
{{- if not $svcPortName }}
  {{- $svcPortName = (first .Values.service.ports).name }}
{{- end }}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "github-actions-example.fullname" . }}
  labels:
    {{- include "github-actions-example.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    external-dns.alpha.kubernetes.io/hostname: "{{ .Values.ingress.hostname }}"
    external-dns.alpha.kubernetes.io/ttl: "60"
    {{- if .Values.ingress.acmCertArn }}
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.ingress.acmCertArn }}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | default "/" }}
            pathType: {{ .Values.ingress.pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "github-actions-example.fullname" . }}
                port:
                  name: {{ $svcPortName }}
{{- end }}
