apiVersion: v1
kind: Service
metadata:
  name: {{ include "github-actions-example.fullname" . }}
  labels:
    {{- include "github-actions-example.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "github-actions-example.selectorLabels" . | nindent 4 }}
