apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name | default (include "nodejs.fullname" .) }}
  labels:
    {{- include "nodejs.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "nodejs.selectorLabels" . | nindent 4 }}
