replicaCount: 1

image:
  repository: 806210429052.dkr.ecr.ap-southeast-2.amazonaws.com/github-actions-example
  tag: "" # To be overridden by CI/CD with a specific version/commit SHA
  pullPolicy: IfNotPresent

containerPort: 3000 # The port your Node.js application listens on inside the container

service:
  type: ClusterIP
  annotations: {}  # Will be populated by Jinja template
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
      
ingress:
  enabled: true
  className: "nginx"
  hostname: "{{ app_name }}.bunnycloud.xyz"
  path: "/"
  pathType: "Prefix"
  acmCertArn: "{{ acm_certificate_arn }}"
  tls: false
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "nginx.ingress.kubernetes.io/ssl-redirect": "false"
    "nginx.ingress.kubernetes.io/force-ssl-redirect": "false"
    "external-dns.alpha.kubernetes.io/hostname": "{{ app_name }}.bunnycloud.xyz."
    "external-dns.alpha.kubernetes.io/ttl": "60"
    "service.beta.kubernetes.io/aws-load-balancer-backend-protocol": "http"
    "service.beta.kubernetes.io/aws-load-balancer-ssl-ports": "https"

  # tls:
  #   - hosts:
  #       - "github-actions-example.bunnycloud.xyz"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with
  # constrained resources, such as Minikube. If you do want to specify resources, uncomment the
  # following lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /status # Example path, adjust to your app's health check endpoint
    port: 3000  # Use the actual port number instead of template expression
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /status # Example path, adjust to your app's readiness endpoint
    port: 3000  # Use the actual port number instead of template expression
  initialDelaySeconds: 5
  periodSeconds: 10

externalDNS:
  elbTarget: ""

server:
  serviceAccount:
    create: false
    name: argocd-server
  extraArgs:
    - --insecure
