replicaCount: 1

image:
  repository: 806210429052.dkr.ecr.ap-southeast-2.amazonaws.com/github-actions-example
  tag: "" # To be overridden by CI/CD with a specific version/commit SHA
  pullPolicy: IfNotPresent

containerPort: 3000 # The port your Node.js application listens on inside the container


service:
  name: nodejs-service-https
  type: LoadBalancer # Use LoadBalancer for external access, or ClusterIP for internal access
  port: 443
  targetPort: 3000

ingress:
  enabled: true
  className: "nginx" # Specify your IngressClass if needed, e.g., "nginx", "alb"
  host: github-actions-example.bunnycloud.xyz
  sslCertArn: "${aws_acm_certificate.this.arn}"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with
  # constrained resources, such as Minikube. If you do want to specify resources, uncomment the
  # following lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

livenessProbe:
  httpGet:
    path: /status # Example path, adjust to your app's health check endpoint
    port: http # Refers to the containerPort
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  httpGet:
    path: /readyz # Example path, adjust to your app's readiness endpoint
    port: http # Refers to the containerPort
  initialDelaySeconds: 5
  periodSeconds: 10
