
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::806210429052:role/bastion-role
      username: bastion
      groups:
      - system:masters
