#
# Required variables for this template:
#   aws_account_id: AWS Account number (string)
#   aws_region: AWS Region (e.g., ap-southeast-2)
#   app_name: ECR repository name (string)
#   image_tag: Tag for the container image (string)
#   acm_certificate_arn: ACM Certificate ARN for ALB (string)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha
  namespace: argocd # Your ArgoCD installation namespace
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Ensures Kubernetes resources are deleted when the ArgoCD Application is deleted
spec:
  project: default # Your ArgoCD project
  source:
    repoURL: https://github.com/kbunnyjoel/github-actions-example # URL of the Git repository where your Helm chart is located
    targetRevision: main # Git branch/tag/commit to sync from
    path: apps/gha/chart # Path to the Helm chart within the repository (e.g., apps/nodejs/chart)
    helm:
      values: |
        replicaCount: 1 # Default replica count, can be overridden
        image:
          repository: docker.io/1073286/github-actions-example # Docker Hub image repository
          tag: 779af83b8effc3f7b0ee323788148a52aa4a05f4
          pullPolicy: IfNotPresent

        containerPort: 3000 # The port your Node.js application listens on inside the container

        service:
          type: ClusterIP # Changed from LoadBalancer
          ports: # Ensure your Helm chart's service template uses this structure
            - name: http # Name of the port, referenced by Ingress
              port: 80 # Service's port
              targetPort: 3000 # Target the containerPort directly, assuming it's 3000 as per containerPort and probes.
              protocol: TCP
          # annotations: {} # Service annotations are generally not needed for ClusterIP with Ingress
          
        # SSL/TLS is terminated at the AWS NLB using ACM; do NOT enable TLS/SSL or redirects at the Ingress level.
        ingress:
          enabled: true
          className: "alb"  # Specify ALB Ingress Class
          hostname: "gha.bunnycloud.xyz" # Your application's actual hostname
          path: "/"
          pathType: "Prefix"
          port: 3000 # Ensure this matches the containerPort
          annotations:
            kubernetes.io/ingress.class: "alb" # Ensures ALB controller picks it up
            alb.ingress.kubernetes.io/scheme: internet-facing
            alb.ingress.kubernetes.io/redirect-http-to-https: "true" # Redirect HTTP to HTTPS
            alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
            alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:ap-southeast-2:806210429052:certificate/4790786b-6586-43ea-adc2-61d6199e1197" # Crucial for HTTPS on ALB
            alb.ingress.kubernetes.io/target-type: ip # Good for EKS, especially Fargate
            alb.ingress.kubernetes.io/healthcheck-path: "/status"
            alb.ingress.kubernetes.io/healthcheck-headers: '[{"name":"x-api-key","value":"test123"}]'
            alb.ingress.kubernetes.io/backend-protocol: HTTP # ALB terminates SSL, forwards HTTP
            alb.ingress.kubernetes.io/group.name: gha
            external-dns.alpha.kubernetes.io/ttl: "60"
            external-dns.alpha.kubernetes.io/hostname: "gha.bunnycloud.xyz."
            alb.ingress.kubernetes.io/load-balancer-attributes: deletion_protection.enabled=false
            alb.ingress.kubernetes.io/force-update: "$(date +%s)"

        # Define resource requests and limits for your application pods
        resources: {} # Leave empty to use Helm chart defaults or override as needed
        #  limits:
        #    cpu: 200m
        #    memory: 256Mi
        #  requests:
        #    cpu: 100m
        #    memory: 128Mi

        livenessProbe:
          httpGet:
            path: /status # Your application's liveness probe endpoint
            port: 3000   # Target the containerPort directly or a named port on the container (e.g., 'http')
          initialDelaySeconds: 15
          periodSeconds: 20

        readinessProbe:
          httpGet:
            path: /status # Your application's readiness probe endpoint
            port: 3000    # Target the containerPort directly or a named port on the container
          initialDelaySeconds: 5
          periodSeconds: 10

        # No longer using externalDNS.elbTarget as it causes template rendering issues
  destination:
    server: https://kubernetes.default.svc # Target Kubernetes API server
    namespace: github-actions-example # Namespace to deploy the application into (e.g., "nodejs")
  syncPolicy:
    automated:
      prune: true # Automatically delete resources that are no longer defined in Git
      selfHeal: true # Automatically sync if the live state drifts from the desired state in Git
    syncOptions:
    - CreateNamespace=true # Automatically create the target namespace if it doesn't exist
 