name: Nodejs CI with code coverage

on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'First number to add'
        required: true
        type: number
      number2:
        description: 'Second number to add'
        required: true
        type: number

  push:
    branches: [ main ]
  pull_request:
    branches: [ main, 'feature/*' ]

jobs:
  buil-and-test:
    runs-on: ubuntu-latest

    env:
      NUMBER1: ${{ github.event.inputs.number1 }}
      NUMBER2: ${{ github.event.inputs.number2 }}

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test on multiple Node.js versions

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List files in workspace
      run: ls -l
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm ci # Use ci for cleaner installs from package-lock.json

    - name: Run tests and collect coverage
      run: npm test # This will now run 'jest --coverage'

    - name: Debug input values
      run: |
        echo "NUMBER1=${NUMBER1}"
        echo "NUMBER2=${NUMBER2}"
      env:
        NUMBER1: ${{ github.event.inputs.number1 }}
        NUMBER2: ${{ github.event.inputs.number2 }}

    - name: Run npm start with inputs
      run: npm start
      env:
        INPUT_NUMBER1: ${{ github.event.inputs.number1 }}
        INPUT_NUMBER2: ${{ github.event.inputs.number2 }}

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-node-${{ matrix.node-version }}
        path: coverage/ # Upload the entire coverage directory
