name: Nodejs CI with code coverage

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the person to greet'
        required: true
        default: 'World from workflow_dispatch'
        type: string
      greeting:
        type: boolean
        description: 'Whether to greet or not'
        required: true

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buil-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x] # Test on multiple Node.js versions

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        # cache: 'npm' # Cache npm dependencies

    - name: Install dependencies
      run: npm install # Use ci for cleaner installs from package-lock.json

    - name: Run tests and collect coverage
      run: npm test # This will now run 'jest --coverage'

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-node-${{ matrix.node-version }}
        path: coverage/ # Upload the entire coverage directory
